// <auto-generated />
namespace TUAN3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ThemCoursevaCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThemCoursevaCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202303060302042_Them Course va Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
